### PR TITLE
Reducing the size of the box shadow

### PR DESCRIPTION
**Pull request by thejamesdempsey**
Reducing the box shadow better matched our brand and makes it look more like a border.

### CODE REVIEW

**Comment by JasonUSC** [comment]
Can I get a little more information about what this is about before it goes
through?

_Jason Chandler_
Director of Web & Social Media
Digital Strategies, Cru
321-331-9576
jason.chandler@cru.org
www.cru.org

**Comment by mattgasior** [comment]
The new navigation is going to necessitate some flattening of the site. We do need to coordinate these design changes.

@thejamesdempsey – the tile components don't use .box-shadow--thin. So we may need to add this in there.

**Comment by JasonUSC** [comment]
I would like to postpone this change as I have not seen it and it will move
the "Give" section farther away from the rest of the site.

_Jason Chandler_
Director of Web & Social Media
Digital Strategies, Cru
321-331-9576
jason.chandler@cru.org
www.cru.org

**Comment by thejamesdempsey** [comment]
@mattgasior I did not realize that. I will check it out

**Pull request closed without merging**
