### PR TITLE
Adds padding to borders around article pages in ie

### PR DESCRIPTION
**Pull request by elikem**

### CODE REVIEW

**Comment by JasonUSC** [comment]
Why are fonts and images now in a relative folders (images/ and fonts/) instead of absolute (/images/ and /fonts/?)

**Comment by elikem** [comment]
@sixtrojans this is a change that @thejamesdempsey introduced to `patterns` here  https://github.com/CruGlobal/patterns/commit/b4e18b4bdf68c4cd141d52e2f1d0b013cd697d01 and here  https://github.com/CruGlobal/patterns/commit/adfa26db9009ba1cd99cb4f18718d7e25a0cbda6.

This according to the commit messages this is a fix address image path problems between patterns and cq.

**Comment by elikem** [comment]
@sixtrojans I'll add the absolute paths in patterns and update this pull request.

**Comment by JasonUSC** [comment]
@thejamesdempsey correctly set the folders to absolute paths; in this new code, unless I am reading it wrong, it would undo that and make it relative again. See for example line 4924 in this new block of code:     background: url("images/cru-logo.png");

**Comment by elikem** [comment]
@sixtrojans @thejamesdempsey must have forgotten to correct this image path. I've corrected it.
My fix is located here https://github.com/CruGlobal/CruOrg/blob/7fd6e1555984c9fb8911c8d1b912bdce4998749e/CQFiles/CruOrgApp/%40JCR_ROOT/apps/CruOrgApp/components/page/htmlbase/clientlibs-ie/css/style.ie.css#L4478 on line 4478 to `.layout-single-column` (changed the width from 900 to 700).

screenshot 2014-08-28 20 23 13

**Comment by thejamesdempsey** [comment]
Somehow the paths got overwritten. Not sure what happened. I will correct it tomorrow

**Pull request merged**
