### PR TITLE
Fix shares

### PR DESCRIPTION
**Pull request by elikem**

### CODE REVIEW

**Comment by elikem** [comment]
@thejamesdempsey take a look at this

**Comment by mattgasior** [comment]
It looks like the like button on the articles is shifted down after this fix.

**Comment by elikem** [comment]
@thejamesdempsey _shame.scss only exists for sass-main and not referenced in sass-ie. 
Can you confirm that this should be correct?
Thanks.

**Comment by thejamesdempsey** [comment]
@elikem that is a mistake. It should be referenced in both.

## 

Jimmy Dempsey
Web Developer and Front-end Architect
Digital Strategies, Cru

---

thejamesdempsey.com

**Pull request merged**
