### PR TITLE
Fix render blocking fonts

### PR DESCRIPTION
**Pull request by thejamesdempsey**

### CODE REVIEW

**Comment by JasonUSC** [comment]
@thejamesdempsey it looks like you made changes to TypeKit but I'm having trouble following what you did. There is something call font flashing where if a page renders too quickly before fonts are downloaded that you get unstyled text that flashes before being styled correctly. We added settings to slow down the page render until the fonts have downloaded. Are you reversing these settings?

**Comment by mattgasior** [comment]
If I'm reading it correctly, this commit simply removes the line breaks in the script. None of the settings are changed. @thejamesdempsey can you confirm?

**Comment by thejamesdempsey** [comment]
Jason. Yes I am. In talking with @tdaffron we both agreed that FOUT is better than using a render blocking piece of script which slows down the load of the entire page. This has a detrimental effect on mobile. There are so many other factors which slow a web page down that intentionally slowing one down does not make sense. We are getting FOUT on initial page load but then the font gets cached which should catch it a majority of the time. Currently none of the page content will load until the entire TypeKit script is downloaded.

**Comment by JasonUSC** [comment]
@mattgasior There is new typekit code (the code itself is different) and there is also a new browser test around clientlibs that detects IE version. I'd like to know what changed in the TypeKit code and where the new code came from.

**Comment by thejamesdempsey** [comment]
http://blog.typekit.com/2011/05/25/loading-typekit-fonts-asynchronously/

**Pull request closed without merging**
