### PR TITLE
Style modifications

### PR DESCRIPTION
**Pull request by mattdrees**
I'd like to suggest a few changes to the checkstyle.xml doc. 
1. My team has recently decided we want to try to limit method bodies to 15 lines long. Shorter methods are easier to read and also discourage too much unrelated stuff happening in a given method.
2. I like google's [style guide rules for whitespace](http://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.6.2-horizontal-whitespace) around commas and other tokens/operators/keywords. I've incorporated their whitespace rules pretty much verbatim.

Do these changes look reasonable? @palecio-xumak , I'm guessing this is your call, but let me know if I should ask someone else instead.

### CODE REVIEW

**Comment by joransky-xk** [comment]
Matt,  

I’ve always thought line limits for methods is kind of arbitrary. Personally, I would encourage verbosity over he number of lines. Certainly, doing things efficiently is paramount, but compilers do a very good job these days optimizing byte code, so if wiring code in 18 lines means it’s more understandable, I’d think we would want to allow it.

Joshua Oransky  |  Head of Technical Excellence, Chief Architect  |  XumaK  
Global Integration Team  |  Professional Services

JOransky@XumaK.com  |  +1/805.216.3069  |  @XumaKJosh  |  www.XumaK.com

JSR 170/283: Content Repository for Java TM Technology API

**Comment by mattdrees** [comment]
I'm all for good naming (which is what I think you mean by verbosity). And it's part of why I like shorter methods -- you end up with more methods, each with specific names. These specific names make it easier to read the code.

Efficiency (byte code/runtime efficiency, anyway) wasn't a reason for my wanting short methods. I really only care about readability. So if there are cases where an 18-line method is more readable than two 9-line methods, then I agree we'd want to allow it.  I just think those cases are really really rare. You don't think so?

**Comment by joransky-xk** [comment]
Fair enough. Certainly stuff can be broken part into smaller methods and assembled into larger logic.  

One of the by products I've seen of this, however, is a class that keeps a lot of state between methods. Obviously minimizing side-effects and keeping immutable classes needs to be part of this.  

In the end, as long as it flags it rather than outright fails it, it's good.

**Comment by mattdrees** [comment]
Ok yeah, I'm happy to compromise with a warning. I'll edit the checkstyle.xml in this PR.

**Comment by mattdrees** [comment]
Modified.

**Comment by palecio-xumak** [comment]
Hi Matt, I completely agree with the second change. For the first one I think it's a good idea to encourage short method bodies, but we shouldn't enforce it. So a warning should be fine.

**Comment by mattdrees** [comment]
Okeydoke, sounds like we're in agreement then. I'll merge the PR.

**Pull request merged**
